In [1]:
import numpy as np
import pandas as pd

In [2]:

dict = {
    "name" : ['soni', 'sapna', 'skill','shubh'],
    "marks" :[87, 45, 23, 90],
    "city" :['rampur', 'kolkata', 'barauli', 'antartika']
}

In [3]:
df=pd.DataFrame(dict)

In [4]:
df

    name  marks       city
0   soni     87     rampur
1  sapna     45    kolkata
2  skill     23    barauli
3  shubh     90  antartika

In [5]:
df.to_csv('friends.csv')

In [6]:
df.to_csv('friends_index_false.csv', index=False)

In [7]:
df.head(2)

    name  marks     city
0   soni     87   rampur
1  sapna     45  kolkata

In [8]:
df.tail(3)

    name  marks       city
1  sapna     45    kolkata
2  skill     23    barauli
3  shubh     90  antartika

In [9]:
df.describe()

           marks
count   4.000000
mean   61.250000
std    32.745229
min    23.000000
25%    39.500000
50%    66.000000
75%    87.750000
max    90.000000

In [10]:
df.index = ['first', 'second', 'third', 'fourth']

In [11]:
df

         name  marks       city
first    soni     87     rampur
second  sapna     45    kolkata
third   skill     23    barauli
fourth  shubh     90  antartika

In [12]:
# series and Dataframe

In [13]:
ser = pd.Series(np.random.rand(34))

In [14]:
ser

0     0.512900
1     0.589344
2     0.929423
3     0.684991
4     0.788124
5     0.820221
6     0.677613
7     0.945796
8     0.764576
9     0.080312
10    0.820805
11    0.636814
12    0.226714
13    0.753365
14    0.007104
15    0.515190
16    0.122839
17    0.635500
18    0.664846
19    0.688144
20    0.326442
21    0.100992
22    0.409659
23    0.988977
24    0.557406
25    0.431209
26    0.305461
27    0.242707
28    0.851531
29    0.857487
30    0.134227
31    0.338935
32    0.641316
33    0.127968
dtype: float64

In [15]:
type(ser)

pandas.core.series.Series

In [16]:
newdf  = pd.DataFrame(np.random.rand(221,5), index = np.arange(221))

In [17]:
newdf

            0         1         2         3         4
0    0.553493  0.969262  0.367898  0.538308  0.389987
1    0.051481  0.026628  0.625347  0.205217  0.035287
2    0.812787  0.687916  0.371589  0.667374  0.960579
3    0.721710  0.676099  0.293961  0.040063  0.904107
4    0.738276  0.018562  0.473428  0.456314  0.078340
..        ...       ...       ...       ...       ...
216  0.750043  0.612340  0.917628  0.272993  0.801011
217  0.908143  0.471073  0.815198  0.871070  0.605915
218  0.448563  0.568244  0.247561  0.345276  0.261476
219  0.084700  0.370118  0.674171  0.295923  0.117947
220  0.419634  0.221161  0.626660  0.641140  0.575044

[221 rows x 5 columns]

In [18]:
type(newdf)

pandas.core.frame.DataFrame

In [19]:
newdf.describe()

                0           1           2           3           4
count  221.000000  221.000000  221.000000  221.000000  221.000000
mean     0.521379    0.504052    0.486217    0.483886    0.475335
std      0.292821    0.290195    0.284315    0.282174    0.281766
min      0.002981    0.000407    0.000501    0.000609    0.006912
25%      0.258218    0.236968    0.244009    0.260695    0.252062
50%      0.541812    0.514516    0.485250    0.456314    0.464857
75%      0.761401    0.746891    0.740886    0.742815    0.729291
max      0.999524    0.991633    0.993926    0.999324    0.998367

In [20]:
newdf.dtypes

0    float64
1    float64
2    float64
3    float64
4    float64
dtype: object

In [21]:
newdf.head()

          0         1         2         3         4
0  0.553493  0.969262  0.367898  0.538308  0.389987
1  0.051481  0.026628  0.625347  0.205217  0.035287
2  0.812787  0.687916  0.371589  0.667374  0.960579
3  0.721710  0.676099  0.293961  0.040063  0.904107
4  0.738276  0.018562  0.473428  0.456314  0.078340

In [22]:
newdf[0][0] = "soni"

C:\Users\zisha\AppData\Local\Temp\ipykernel_8124\3001414116.py:1: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  newdf[0][0] = "soni"
C:\Users\zisha\AppData\Local\Temp\ipykernel_8124\3001414116.py:1: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'soni' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  newdf[0][0] = "soni"

In [23]:
newdf

            0         1         2         3         4
0        soni  0.969262  0.367898  0.538308  0.389987
1    0.051481  0.026628  0.625347  0.205217  0.035287
2    0.812787  0.687916  0.371589  0.667374  0.960579
3     0.72171  0.676099  0.293961  0.040063  0.904107
4    0.738276  0.018562  0.473428  0.456314  0.078340
..        ...       ...       ...       ...       ...
216  0.750043  0.612340  0.917628  0.272993  0.801011
217  0.908143  0.471073  0.815198  0.871070  0.605915
218  0.448563  0.568244  0.247561  0.345276  0.261476
219    0.0847  0.370118  0.674171  0.295923  0.117947
220  0.419634  0.221161  0.626660  0.641140  0.575044

[221 rows x 5 columns]

In [24]:
newdf.index

Index([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,
       ...
       211, 212, 213, 214, 215, 216, 217, 218, 219, 220],
      dtype='int64', length=221)

In [25]:
newdf.columns

RangeIndex(start=0, stop=5, step=1)

In [26]:
newdf.to_numpy()

array([['soni', 0.9692617094094187, 0.36789813078366684,
        0.5383075941136395, 0.38998721491110877],
       [0.05148106832169497, 0.026627620587712397, 0.6253470104902876,
        0.20521667837223634, 0.03528689661850937],
       [0.812787360763178, 0.6879162787188431, 0.3715893959998824,
        0.6673735249088041, 0.9605791854782474],
       ...,
       [0.44856262905740896, 0.5682436244420848, 0.2475613285542364,
        0.3452757541780367, 0.2614759202352721],
       [0.08469966157541309, 0.3701181633133571, 0.6741711103081135,
        0.2959230666306645, 0.11794713568799997],
       [0.41963403816021283, 0.22116148871533903, 0.6266602675570935,
        0.641139600538071, 0.575044094643139]],
      shape=(221, 5), dtype=object)

In [27]:
newdf.head()

          0         1         2         3         4
0      soni  0.969262  0.367898  0.538308  0.389987
1  0.051481  0.026628  0.625347  0.205217  0.035287
2  0.812787  0.687916  0.371589  0.667374  0.960579
3   0.72171  0.676099  0.293961  0.040063  0.904107
4  0.738276  0.018562  0.473428  0.456314  0.078340

In [28]:
newdf.T

,0,1,2,3,4,5,6,7,8,9,...,211,212,213,214,215,216,217,218,219,220
0,soni,0.051481,0.812787,0.72171,0.738276,0.206414,0.532224,0.969644,0.544665,0.634951,...,0.237285,0.195536,0.198424,0.146236,0.965096,0.750043,0.908143,0.448563,0.0847,0.419634
1,0.969262,0.026628,0.687916,0.676099,0.018562,0.316735,0.297958,0.004109,0.947014,0.972109,...,0.840817,0.581626,0.641278,0.360792,0.786797,0.61234,0.471073,0.568244,0.370118,0.221161
2,0.367898,0.625347,0.371589,0.293961,0.473428,0.000501,0.258205,0.255246,0.320745,0.261784,...,0.25803,0.691286,0.276449,0.640633,0.653457,0.917628,0.815198,0.247561,0.674171,0.62666
3,0.538308,0.205217,0.667374,0.040063,0.456314,0.78721,0.294227,0.000609,0.50241,0.076065,...,0.751338,0.333341,0.075333,0.148222,0.097876,0.272993,0.87107,0.345276,0.295923,0.64114
4,0.389987,0.035287,0.960579,0.904107,0.07834,0.661822,0.09526,0.038762,0.425666,0.252062,...,0.299798,0.076569,0.466556,0.802204,0.964564,0.801011,0.605915,0.261476,0.117947,0.575044

In [29]:
newdf.head()

          0         1         2         3         4
0      soni  0.969262  0.367898  0.538308  0.389987
1  0.051481  0.026628  0.625347  0.205217  0.035287
2  0.812787  0.687916  0.371589  0.667374  0.960579
3   0.72171  0.676099  0.293961  0.040063  0.904107
4  0.738276  0.018562  0.473428  0.456314  0.078340

In [30]:
newdf.sort_index(axis = 1, ascending=False)

            4         3         2         1         0
0    0.389987  0.538308  0.367898  0.969262      soni
1    0.035287  0.205217  0.625347  0.026628  0.051481
2    0.960579  0.667374  0.371589  0.687916  0.812787
3    0.904107  0.040063  0.293961  0.676099   0.72171
4    0.078340  0.456314  0.473428  0.018562  0.738276
..        ...       ...       ...       ...       ...
216  0.801011  0.272993  0.917628  0.612340  0.750043
217  0.605915  0.871070  0.815198  0.471073  0.908143
218  0.261476  0.345276  0.247561  0.568244  0.448563
219  0.117947  0.295923  0.674171  0.370118    0.0847
220  0.575044  0.641140  0.626660  0.221161  0.419634

[221 rows x 5 columns]

In [31]:
newdf.sort_index(axis=0, ascending = False)

            0         1         2         3         4
220  0.419634  0.221161  0.626660  0.641140  0.575044
219    0.0847  0.370118  0.674171  0.295923  0.117947
218  0.448563  0.568244  0.247561  0.345276  0.261476
217  0.908143  0.471073  0.815198  0.871070  0.605915
216  0.750043  0.612340  0.917628  0.272993  0.801011
..        ...       ...       ...       ...       ...
4    0.738276  0.018562  0.473428  0.456314  0.078340
3     0.72171  0.676099  0.293961  0.040063  0.904107
2    0.812787  0.687916  0.371589  0.667374  0.960579
1    0.051481  0.026628  0.625347  0.205217  0.035287
0        soni  0.969262  0.367898  0.538308  0.389987

[221 rows x 5 columns]

In [32]:
newdf.head()

          0         1         2         3         4
0      soni  0.969262  0.367898  0.538308  0.389987
1  0.051481  0.026628  0.625347  0.205217  0.035287
2  0.812787  0.687916  0.371589  0.667374  0.960579
3   0.72171  0.676099  0.293961  0.040063  0.904107
4  0.738276  0.018562  0.473428  0.456314  0.078340

In [33]:
type(newdf[0])

pandas.core.series.Series

In [34]:
newdf.loc[0,0] = 55    # set new value

In [35]:
newdf.head(2)

          0         1         2         3         4
0        55  0.969262  0.367898  0.538308  0.389987
1  0.051481  0.026628  0.625347  0.205217  0.035287

In [36]:
newdf.columns = list("ABCDE")

In [37]:
newdf.head(2)

          A         B         C         D         E
0        55  0.969262  0.367898  0.538308  0.389987
1  0.051481  0.026628  0.625347  0.205217  0.035287

In [38]:

newdf.loc[0,0] = 8888888

In [39]:
newdf

            A         B         C         D         E          0
0          55  0.969262  0.367898  0.538308  0.389987  8888888.0
1    0.051481  0.026628  0.625347  0.205217  0.035287        NaN
2    0.812787  0.687916  0.371589  0.667374  0.960579        NaN
3     0.72171  0.676099  0.293961  0.040063  0.904107        NaN
4    0.738276  0.018562  0.473428  0.456314  0.078340        NaN
..        ...       ...       ...       ...       ...        ...
216  0.750043  0.612340  0.917628  0.272993  0.801011        NaN
217  0.908143  0.471073  0.815198  0.871070  0.605915        NaN
218  0.448563  0.568244  0.247561  0.345276  0.261476        NaN
219    0.0847  0.370118  0.674171  0.295923  0.117947        NaN
220  0.419634  0.221161  0.626660  0.641140  0.575044        NaN

[221 rows x 6 columns]

In [40]:
newdf=newdf.drop(0, axis=1)

In [41]:
newdf.head()

          A         B         C         D         E
0        55  0.969262  0.367898  0.538308  0.389987
1  0.051481  0.026628  0.625347  0.205217  0.035287
2  0.812787  0.687916  0.371589  0.667374  0.960579
3   0.72171  0.676099  0.293961  0.040063  0.904107
4  0.738276  0.018562  0.473428  0.456314  0.078340

In [42]:
newdf.loc[[1,2], ['C', 'D']]

          C         D
1  0.625347  0.205217
2  0.371589  0.667374

In [43]:
newdf.loc[:,['A', 'B']]

            A         B
0          55  0.969262
1    0.051481  0.026628
2    0.812787  0.687916
3     0.72171  0.676099
4    0.738276  0.018562
..        ...       ...
216  0.750043  0.612340
217  0.908143  0.471073
218  0.448563  0.568244
219    0.0847  0.370118
220  0.419634  0.221161

[221 rows x 2 columns]

In [44]:
newdf.loc[[1,2],:]

          A         B         C         D         E
1  0.051481  0.026628  0.625347  0.205217  0.035287
2  0.812787  0.687916  0.371589  0.667374  0.960579

In [45]:
newdf.loc[(newdf['A']<0.3)]

            A         B         C         D         E
1    0.051481  0.026628  0.625347  0.205217  0.035287
5    0.206414  0.316735  0.000501  0.787210  0.661822
16   0.250439  0.891061  0.296321  0.264082  0.028003
23   0.164733  0.233732  0.486565  0.421668  0.230080
36   0.128424  0.574709  0.610476  0.247907  0.369976
..        ...       ...       ...       ...       ...
211  0.237285  0.840817  0.258030  0.751338  0.299798
212  0.195536  0.581626  0.691286  0.333341  0.076569
213  0.198424  0.641278  0.276449  0.075333  0.466556
214  0.146236  0.360792  0.640633  0.148222  0.802204
219    0.0847  0.370118  0.674171  0.295923  0.117947

[66 rows x 5 columns]

In [46]:
newdf.head(2)

          A         B         C         D         E
0        55  0.969262  0.367898  0.538308  0.389987
1  0.051481  0.026628  0.625347  0.205217  0.035287

In [47]:
newdf.iloc[0,4]

np.float64(0.38998721491110877)

In [48]:
newdf.iloc[[0,5], [1,2]]

          B         C
0  0.969262  0.367898
5  0.316735  0.000501

In [49]:
newdf.drop([0])

            A         B         C         D         E
1    0.051481  0.026628  0.625347  0.205217  0.035287
2    0.812787  0.687916  0.371589  0.667374  0.960579
3     0.72171  0.676099  0.293961  0.040063  0.904107
4    0.738276  0.018562  0.473428  0.456314  0.078340
5    0.206414  0.316735  0.000501  0.787210  0.661822
..        ...       ...       ...       ...       ...
216  0.750043  0.612340  0.917628  0.272993  0.801011
217  0.908143  0.471073  0.815198  0.871070  0.605915
218  0.448563  0.568244  0.247561  0.345276  0.261476
219    0.0847  0.370118  0.674171  0.295923  0.117947
220  0.419634  0.221161  0.626660  0.641140  0.575044

[220 rows x 5 columns]

In [50]:
newdf.drop(['A','D'], axis=1, inplace=True)

In [51]:
newdf

            B         C         E
0    0.969262  0.367898  0.389987
1    0.026628  0.625347  0.035287
2    0.687916  0.371589  0.960579
3    0.676099  0.293961  0.904107
4    0.018562  0.473428  0.078340
..        ...       ...       ...
216  0.612340  0.917628  0.801011
217  0.471073  0.815198  0.605915
218  0.568244  0.247561  0.261476
219  0.370118  0.674171  0.117947
220  0.221161  0.626660  0.575044

[221 rows x 3 columns]

In [52]:
newdf.head()

          B         C         E
0  0.969262  0.367898  0.389987
1  0.026628  0.625347  0.035287
2  0.687916  0.371589  0.960579
3  0.676099  0.293961  0.904107
4  0.018562  0.473428  0.078340

In [53]:
newdf.reset_index(drop=True,inplace=True)

In [54]:
newdf.head(3)

          B         C         E
0  0.969262  0.367898  0.389987
1  0.026628  0.625347  0.035287
2  0.687916  0.371589  0.960579

In [55]:
newdf['B'].isnull()

0      False
1      False
2      False
3      False
4      False
       ...
216    False
217    False
218    False
219    False
220    False
Name: B, Length: 221, dtype: bool

In [56]:
newdf['B'] = None

In [57]:
newdf

        B         C         E
0    None  0.367898  0.389987
1    None  0.625347  0.035287
2    None  0.371589  0.960579
3    None  0.293961  0.904107
4    None  0.473428  0.078340
..    ...       ...       ...
216  None  0.917628  0.801011
217  None  0.815198  0.605915
218  None  0.247561  0.261476
219  None  0.674171  0.117947
220  None  0.626660  0.575044

[221 rows x 3 columns]

In [58]:
dict = {
   "year" : [2000, 2001, 2002, 2003, 2004],
    "india" :[5000, 6000, 7000, 8000, 9000],
    "china" :[400, 5000, 6000, 7000, 8000],
    "america" : [800, 9000, 15000, 18000, 20000],
    "japan" : [300, 4000, 8000, 9000, 15000]

}

In [120]:
an=pd.DataFrame(dict)

In [123]:
an

   year  india  china  america  japan
0  2000   5000    400      800    300
1  2001   6000   5000     9000   4000
2  2002   7000   6000    15000   8000
3  2003   8000   7000    18000   9000
4  2004   9000   8000    20000  15000

In [125]:
an.to_csv('soni.csv')